server:
  port: 8090
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:///127.0.0.1:3306/eNovel?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: root
    password:
    thymeleaf:
      cache: false
      prefix: file:src/main/resources/templates/
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true
    jpa:
      properties:
        hibernate:
          format_sql: 'true'
          show_sql: 'true'
    logging:
      level:
        # SQL? ??? ?? ????, SQL? ??? ??
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE
        org.hibernate.orm.jdbc.extract: TRACE
        org.springframework.transaction.interceptor: TRACE
      hibernate:
        ddl-auto: update
      subject:
        member:
          registration: Thank you for joining our site!
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 500MB





