spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: CLIENT_ID
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  order:
    cancelableSeconds:
  genFileDirPath:
  resourcePath:
  requestPath:
  originPath:
  paymentSecretKey: